### PR TITLE
feat: use rust based tooling for hex to uf2 conversion

### PR DESCRIPTION
**Pull request by fhanrath**
Switch to Rust based tooling for the hex -> uf2 conversion.

I would have preferred to include the whole code into this or RMK related projects, but I wasn't able to make it work due to this repo being a template and the other RMK repos having embedded targets and disable std for all projects (I guess?).

I'm happy to iterate on this merge. Especially regarding where to integrate the conversion code into the RMK project.

The code for the conversion itself can be found here: https://git.sr.ht/~fenris/hex-to-uf2
Feel free to copy the code to an existing or new RMK project.

### CODE REVIEW

**Comment by HaoboGu** [comment]
> but I wasn't able to make it work due to this repo being a template and the other RMK repos having embedded targets and disable std for all projects (I guess?)

The code cannot be directly used in RMK repo since RMK code runs on microcontrollers. The conversion code runs on the host. The conversion should be integrated to the building process.

I believe that you can make it a [cargo command](https://doc.rust-lang.org/cargo/commands/index.html), making it usable by both `cargo-make` and `cargo run`. 

If we can make similar thing like `cargo objcopy` in [cargo-binutils](https://github.com/rust-embedded/cargo-binutils), it would be very great

**Comment by HaoboGu** [comment]
And you can open a PR first for examples and documentations in RMK project as well

**Comment by fhanrath** [comment]
> I believe that you can make it a [cargo command](https://doc.rust-lang.org/cargo/commands/index.html), making it usable by both cargo-make and cargo run.
> 
> If we can make similar thing like cargo objcopy in [cargo-binutils](https://github.com/rust-embedded/cargo-binutils), it would be very great

It already is a cargo command.
I just haven't published it to crates.io yet.

When I try to do
```toml
command = "cargo"
args = [
    "hex-to-uf2",
    "{{project-name}}.hex",
    "{{project-name}}.uf2",
    "--family",
    "{{ uf2_chip_family }}",
]
```

cargo-make complains it can't find hex_to_uf2 on crates.io, so I switched to using the binary directly instead here.
I haven't done so yet. If you're okay with using the binary I'm producing, I can work on that.

> And you can open a PR first for examples and documentations in RMK project as well

sure thing, I will do so!

**Comment by fhanrath** [comment]
I published my tool to crates.io and updated this pull request.

**Comment by fhanrath** [comment]
I've also updated the docs: https://github.com/HaoboGu/rmk/pull/215

**Pull request merged**
